### ISSUE TITLE
Failed to open the serial port

### ISSUE THREAD

**Issue by parmi93** [microsoft/vscode-serial-monitor#159] opened 2024-01-12 13:11 UTC
I can't open any Quectel BG95 modem serial port enumerated on the USB port, I keep getting the error:
**** Failed to open the serial port /dev/ttyUSB3 ****

Other terminals like Putty can open the port without problems (without sudo permission).

Usually as a workaround I restarted the PC and Serial Monitor was able to open the port, but from today this workaround no longer works.

Maybe it's the same problem reported here:
https://github.com/microsoft/vscode-serial-monitor/issues/142

/home/parmi/.config/Code/logs/20240112T132216/window1/exthost/output_logging_20240112T132216/1-Serial Monitor Logging.log
```
2024-01-12T13:22:16.789Z [info] [vscode-serial-monitor] Activating extension
2024-01-12T13:22:17.125Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview -> host]: {"service":"monitorHost","type":"initialize","kind":"request","messageId":0}
2024-01-12T13:22:17.381Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview <- host]: {"service":"monitorHost","type":"initialize","kind":"response","messageId":0,"payload":{"localization":{"displayLanguage":"en","displayLanguageKind":"VSCode"},"ports":[{"portName":"/dev/ttyUSB1","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB2","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB4","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB0","friendlyName":"FTDI","vid":"0403","pid":"6001"},{"portName":"/dev/ttyS0"},{"portName":"/dev/ttyS1"},{"portName":"/dev/ttyS10"},{"portName":"/dev/ttyS11"},{"portName":"/dev/ttyS12"},{"portName":"/dev/ttyS13"},{"portName":"/dev/ttyS14"},{"portName":"/dev/ttyS15"},{"portName":"/dev/ttyS16"},{"portName":"/dev/ttyS17"},{"portName":"/dev/ttyS18"},{"portName":"/dev/ttyS19"},{"portName":"/dev/ttyS2"},{"portName":"/dev/ttyS20"},{"portName":"/dev/ttyS21"},{"portName":"/dev/ttyS22"},{"portName":"/dev/ttyS23"},{"portName":"/dev/ttyS24"},{"portName":"/dev/ttyS25"},{"portName":"/dev/ttyS26"},{"portName":"/dev/ttyS27"},{"portName":"/dev/ttyS28"},{"portName":"/dev/ttyS29"},{"portName":"/dev/ttyS3"},{"portName":"/dev/ttyS30"},{"portName":"/dev/ttyS31"},{"portName":"/dev/ttyS4"},{"portName":"/dev/ttyS5"},{"portName":"/dev/ttyS6"},{"portName":"/dev/ttyS7"},{"portName":"/dev/ttyS8"},{"portName":"/dev/ttyS9"}],"supportedBauds":[300,1200,2400,4800,9600,19200,38400,57600,74880,115200,230400,250000],"loggingSeverity":"warn","closable":"no","settings":{"lineEnding":"\r\n","dataBits":8,"dtr":false,"rts":false,"autoReconnectionEnabled":false,"logFileDirectory":"/home/parmi/Desktop","logFileEnabled":0,"customBaudRates":[]},"fontInformation":{},"timestampFormat":"%H:%M:%S:%L"}}
2024-01-12T13:22:17.381Z [debug] [vscode-serial-monitor.monitor] Received serial monitor initialization response {"localization":{"displayLanguage":"en","displayLanguageKind":"VSCode"},"ports":[{"portName":"/dev/ttyUSB1","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB2","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB4","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB0","friendlyName":"FTDI","vid":"0403","pid":"6001"},{"portName":"/dev/ttyS0"},{"portName":"/dev/ttyS1"},{"portName":"/dev/ttyS10"},{"portName":"/dev/ttyS11"},{"portName":"/dev/ttyS12"},{"portName":"/dev/ttyS13"},{"portName":"/dev/ttyS14"},{"portName":"/dev/ttyS15"},{"portName":"/dev/ttyS16"},{"portName":"/dev/ttyS17"},{"portName":"/dev/ttyS18"},{"portName":"/dev/ttyS19"},{"portName":"/dev/ttyS2"},{"portName":"/dev/ttyS20"},{"portName":"/dev/ttyS21"},{"portName":"/dev/ttyS22"},{"portName":"/dev/ttyS23"},{"portName":"/dev/ttyS24"},{"portName":"/dev/ttyS25"},{"portName":"/dev/ttyS26"},{"portName":"/dev/ttyS27"},{"portName":"/dev/ttyS28"},{"portName":"/dev/ttyS29"},{"portName":"/dev/ttyS3"},{"portName":"/dev/ttyS30"},{"portName":"/dev/ttyS31"},{"portName":"/dev/ttyS4"},{"portName":"/dev/ttyS5"},{"portName":"/dev/ttyS6"},{"portName":"/dev/ttyS7"},{"portName":"/dev/ttyS8"},{"portName":"/dev/ttyS9"}],"supportedBauds":[300,1200,2400,4800,9600,19200,38400,57600,74880,115200,230400,250000],"loggingSeverity":"warn","closable":"no","settings":{"lineEnding":"\r\n","dataBits":8,"dtr":false,"rts":false,"autoReconnectionEnabled":false,"logFileDirectory":"/home/parmi/Desktop","logFileEnabled":0,"customBaudRates":[]},"fontInformation":{},"timestampFormat":"%H:%M:%S:%L"}
2024-01-12T13:22:36.523Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview -> host]: {"service":"monitorHost","type":"initialize","kind":"request","messageId":0}
2024-01-12T13:22:36.656Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview <- host]: {"service":"monitorHost","type":"initialize","kind":"response","messageId":0,"payload":{"localization":{"displayLanguage":"en","displayLanguageKind":"VSCode"},"ports":[{"portName":"/dev/ttyUSB1","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB2","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB4","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB0","friendlyName":"FTDI","vid":"0403","pid":"6001"},{"portName":"/dev/ttyS0"},{"portName":"/dev/ttyS1"},{"portName":"/dev/ttyS10"},{"portName":"/dev/ttyS11"},{"portName":"/dev/ttyS12"},{"portName":"/dev/ttyS13"},{"portName":"/dev/ttyS14"},{"portName":"/dev/ttyS15"},{"portName":"/dev/ttyS16"},{"portName":"/dev/ttyS17"},{"portName":"/dev/ttyS18"},{"portName":"/dev/ttyS19"},{"portName":"/dev/ttyS2"},{"portName":"/dev/ttyS20"},{"portName":"/dev/ttyS21"},{"portName":"/dev/ttyS22"},{"portName":"/dev/ttyS23"},{"portName":"/dev/ttyS24"},{"portName":"/dev/ttyS25"},{"portName":"/dev/ttyS26"},{"portName":"/dev/ttyS27"},{"portName":"/dev/ttyS28"},{"portName":"/dev/ttyS29"},{"portName":"/dev/ttyS3"},{"portName":"/dev/ttyS30"},{"portName":"/dev/ttyS31"},{"portName":"/dev/ttyS4"},{"portName":"/dev/ttyS5"},{"portName":"/dev/ttyS6"},{"portName":"/dev/ttyS7"},{"portName":"/dev/ttyS8"},{"portName":"/dev/ttyS9"}],"supportedBauds":[300,1200,2400,4800,9600,19200,38400,57600,74880,115200,230400,250000],"loggingSeverity":"warn","closable":"yes","settings":{"lineEnding":"\r\n","dataBits":8,"dtr":false,"rts":false,"autoReconnectionEnabled":false,"logFileDirectory":"/home/parmi/Desktop","logFileEnabled":0,"customBaudRates":[]},"fontInformation":{},"timestampFormat":"%H:%M:%S:%L"}}
2024-01-12T13:22:36.656Z [debug] [vscode-serial-monitor.monitor] Received serial monitor initialization response {"localization":{"displayLanguage":"en","displayLanguageKind":"VSCode"},"ports":[{"portName":"/dev/ttyUSB1","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB2","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB4","friendlyName":"Quectel, Incorporated","vid":"2c7c","pid":"0700"},{"portName":"/dev/ttyUSB0","friendlyName":"FTDI","vid":"0403","pid":"6001"},{"portName":"/dev/ttyS0"},{"portName":"/dev/ttyS1"},{"portName":"/dev/ttyS10"},{"portName":"/dev/ttyS11"},{"portName":"/dev/ttyS12"},{"portName":"/dev/ttyS13"},{"portName":"/dev/ttyS14"},{"portName":"/dev/ttyS15"},{"portName":"/dev/ttyS16"},{"portName":"/dev/ttyS17"},{"portName":"/dev/ttyS18"},{"portName":"/dev/ttyS19"},{"portName":"/dev/ttyS2"},{"portName":"/dev/ttyS20"},{"portName":"/dev/ttyS21"},{"portName":"/dev/ttyS22"},{"portName":"/dev/ttyS23"},{"portName":"/dev/ttyS24"},{"portName":"/dev/ttyS25"},{"portName":"/dev/ttyS26"},{"portName":"/dev/ttyS27"},{"portName":"/dev/ttyS28"},{"portName":"/dev/ttyS29"},{"portName":"/dev/ttyS3"},{"portName":"/dev/ttyS30"},{"portName":"/dev/ttyS31"},{"portName":"/dev/ttyS4"},{"portName":"/dev/ttyS5"},{"portName":"/dev/ttyS6"},{"portName":"/dev/ttyS7"},{"portName":"/dev/ttyS8"},{"portName":"/dev/ttyS9"}],"supportedBauds":[300,1200,2400,4800,9600,19200,38400,57600,74880,115200,230400,250000],"loggingSeverity":"warn","closable":"yes","settings":{"lineEnding":"\r\n","dataBits":8,"dtr":false,"rts":false,"autoReconnectionEnabled":false,"logFileDirectory":"/home/parmi/Desktop","logFileEnabled":0,"customBaudRates":[]},"fontInformation":{},"timestampFormat":"%H:%M:%S:%L"}
```

Serial Monitor v0.11.0
OS: Ubuntu 22.04.3 LTS
Visual Studio Code:
- Version: 1.85.1
- Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
- Date: 2023-12-13T09:47:11.635Z
- Electron: 25.9.7
- ElectronBuildId: 25551756
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Linux x64 6.5.0-14-generic snap

**Comment by lawrencerb** [comment] 2024-01-24 17:27
I'm also having trouble connecting to a UART-USB Prolific Adapter.

I managed to successfully perform connection and activity with the same device on a Windows Machine

But both Ubuntu and Fedora displays the same message:
**** Failed to open the serial port /dev/ttyUSB0 ****

I'm able to open connection with other Serial devices.

Using dmesg | grep tty

I've tried communicating between 2 USB-Serial adapters. But I'm getting the same error -32:
[  227.380831] pl2303 ttyUSB1: pl2303_get_line_request - failed: -32
[  227.384994] pl2303 ttyUSB1: pl2303_get_line_request - failed: -32
[  227.385980] pl2303 ttyUSB1: pl2303_get_line_request - failed: -32
[  227.388969] pl2303 ttyUSB1: error sending break = -32
[  234.021402] pl2303 ttyUSB1: error sending break = -32
[  234.126054] pl2303 ttyUSB0: error sending break = -32
[  250.306071] pl2303 ttyUSB0: pl2303_get_line_request - failed: -32
[  250.316000] pl2303 ttyUSB0: pl2303_get_line_request - failed: -32
[  268.288965] pl2303 ttyUSB1: pl2303_get_line_request - failed: -32
[  268.294195] pl2303 ttyUSB1: pl2303_get_line_request - failed: -32
[  297.268640] pl2303 ttyUSB1: error sending break = -32
[  298.531848] pl2303 ttyUSB0: error sending break = -32

My best guess is that something happened on the Linux Driver kernel that does not respond correctly to the VsCdoe Serial Monitor Extension command.

I could, on the same Ubuntu machine, comunicate with the USB-Serial adapter using minicom. But not the Extension.

**Comment by gcampbell-msft** [comment] 2024-01-26 14:18
@parmi93 Could you test these steps: https://github.com/microsoft/vscode-serial-monitor/issues/142#issuecomment-1864644326, and let me know the results? It could be that this, as you pointed out, is the same issue as #142. If so, we'll close this item and link it to the other bug. 

Thanks!

**Comment by parmi93** [comment] 2024-01-26 19:46
I managed to open the `/dev/ttyUSB3` port with the node project (test.zip).

But if I uncomment line 10 of `serialport.ts` I get this error:
<pre><font color="#26A269"><b>parmi@parmi-Dell-G16-7630</b></font>:<font color="#12488B"><b>~/Downloads/test</b></font>$ sudo dmesg | grep tty
[  643.724396] usb 1-8: FTDI USB Serial Device converter now attached to <font color="#C01C28"><b>tty</b></font>USB0
[  650.505375] usb 1-10: GSM modem (1-port) converter now attached to <font color="#C01C28"><b>tty</b></font>USB1
[  650.505573] usb 1-10: GSM modem (1-port) converter now attached to <font color="#C01C28"><b>tty</b></font>USB2
[  650.505766] usb 1-10: GSM modem (1-port) converter now attached to <font color="#C01C28"><b>tty</b></font>USB3
<font color="#26A269"><b>parmi@parmi-Dell-G16-7630</b></font>:<font color="#12488B"><b>~/Downloads/test</b></font>$ npm run build

&gt; serialportexample@1.0.0 build
&gt; tsc -p .

<font color="#26A269"><b>parmi@parmi-Dell-G16-7630</b></font>:<font color="#12488B"><b>~/Downloads/test</b></font>$ node dist/serialport.js
(node:8001) UnhandledPromiseRejectionWarning: Error: Error: Inappropriate ioctl for device, cannot set
(node:8001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8001) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<font color="#26A269"><b>parmi@parmi-Dell-G16-7630</b></font>:<font color="#12488B"><b>~/Downloads/test</b></font>$</pre>

I also noticed that if I try to open the  `/dev/ttyUSB3` port via Serial Monitor after I get the error `**** Failed to open the serial port /dev/ttyUSB3 ****` I can't open the port even with your node project, I have to close Visual Studio Code to be able to reopen the port with your node project, while other tools (like Putty) manage to open the port even with Visual Studio Code still open.

**Comment by gcampbell-msft** [comment] 2024-01-26 20:57
@parmi93 Have you attempted to open the Serial Monitor through the VS Code Serial Monitor extension with various combinations of the RTS and DTR settings? 

I'm currently trying to investigate if there would be a way to work around this external issue, but I wanted to confirm that you've tried that as well. Thanks.

**Comment by parmi93** [comment] 2024-01-29 12:57
Yes, I just tried again Serial Monitor through the VS Code to open the port with all possible combinations of RTS and DTR, none worked.
I also tried all possible combinations of dtr and cts with `serialPort.set()`, none of them worked, It only works if this line is commented out.

**Comment by gcampbell-msft** [comment] 2024-01-29 14:42
@parmi93, thank you for the confirmation. This definitely seems like some issue with the `serialport` library and how it handles the .set() method. 

However, this is happening enough that we should attempt to have some workaround, therefore, I'll mark this bug as external but make a note to investigate providing some kind of workaround.

**Comment by jegjessing** [comment] 2024-02-14 06:17
I too experience this issue, when trying to upload to arduino. Is there no way I can "hack" my way out of this?
Since I cannot monitor using VSC, I have to use Arduino IDE to monitor. And since I do this, the serial port is blocked and therefore I cannot use the upload function in VSC either. A bit annoying :-)

**Comment by gcampbell-msft** [comment] 2024-02-14 14:24
@jegjessing @parmi93 Thank you all for your patience, I understand this is a frustrating issue. Since this is an external issue, there isn't too much we can do about it. 

However, I have plans to, as a workaround, maybe add a setting that disables the RTS and DTR settings for people who are in the situation, or maybe at least not invoke the method call that seems to cause this issue when the requested RTS and DTR settings aren't enabled. 

Would some kind of workaround like this work for you all?

**Comment by parmi93** [comment] 2024-02-14 14:38
I think it should be fine =)

**Comment by gcampbell-msft** [comment] 2024-02-20 16:08
@atomsmith or @parmi93, as a quick sanity check before I implement the workaround idea, could you slightly modify the test I had you run? 

In the `new SerialPort` invocation, could you add `rtscts: true` to the object passed into the constructor? Ensure that the `serialPort.set` method is not commented out, I want to see if actually this has something to do with it. 

Thanks! And thanks for your continued patience with this.

**Comment by parmi93** [comment] 2024-02-21 10:06
I tried to add `rtscts: true` to the constructor, but it still fail to open the port (I tried again all the four combination of `serialPort.set(...)`), I can only open the port when `serialPort.set(...)` is commented out.

**Comment by gcampbell-msft** [comment] 2024-04-03 13:40
@parmi93 @atomsmith @jegjessing @lawrencerb 

Because I've noticed that the bug here on the external dependency: https://github.com/serialport/node-serialport/issues/2636, is only happening on linux, I wonder if a quick way to unblock you all is to only call this method if we're not on linux. 

Could you all manually switch the extension of this zip to .vsix, install it, and test to see if this fixes your issue? 
[vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/14852978/vscode-serial-monitor.zip)

**Comment by parmi93** [comment] 2024-04-03 14:20
Now I don't get any error when I open the port, but I noticed that I get no response from the modem when I send a command, I'm sure that the command reaches the modem because if I send a reboot command the modem restarts, but for some reason serial monitor doesn't show any data it receives, I've tried all combinations of DTR and RTS.

I had also noticed this behaviour with the test.zip you had created, at the time I hadn't said anything simply because I thought that since it was a test it was "expected".

Also another problem I've always noticed, is that when the port is closed "without warning", for example if the device reboots or if I remove the USB cable, the serial monitor detects "the closure" showing the message `---- Closed serial port /dev/ttyUSB3 due to disconnection from the machine ----`, but then it doesn't allow you to open any other port, it keeps showing the error `**** Failed to open the serial port /dev/ttyUSB2 ****`, I have to restart VS Code to be able to reopen the port.

**Comment by gcampbell-msft** [comment] 2024-04-08 14:04
@parmi93

I apologize that I'm needing your all's help for debugging, but since I don't have the required hardware, if you could test again with the test.zip. While testing that program, if you modify line 3, you could test different settings of: rtscts, xon, xoff, etc. This will help me understand what the issue is that's happening. I'm wondering if there are different settings that we need to start the serial port with. 

Additionally, does it fail to open if you call `.set` even with no parameters?

**Comment by parmi93** [comment] 2024-04-15 12:00
I did some digging in the code (`serialport.ts`) and realized that the `serialPort.write()` method is never called, so it was impossible that the device could receive any command I sent.

I then edited the last part of the script `serialport.ts` from:
```js
// on any data into stdin
stdin.on( 'data', function( key ){
  // esc ( end of text )
  if ( key.toString() === '\u001B' ) {
    process.exit();
  }
});
```
to:
```js
// on any data into stdin
stdin.on( 'data', (data) => {
  if ( data.toString() === '\u001B' ) {
      process.exit();
  }
  serialPort.write(data.toString())
});
```
(I've never used NodeJS before so I don't know what I'm doing, but it seems to work)

With the modified script I can successfully send and receive responses from the device.

I also added the following boolean parameters `rtscts`, `xon`, `xoff`, `xany`, `hupcl` to the `SerialPort` constructor setting their values with all 32 possible combinations, in all 32 cases I was always able to send and receive replies from the device successfully.

I tried calling the `set` method without parameters (`serialPort.set({})`), but again the port fails to open with the following error:
```
parmi@parmi-Dell-G16-7630:~/Downloads/test$ node dist/serialport.js
(node:18844) UnhandledPromiseRejectionWarning: Error: Error: Inappropriate ioctl for device, cannot set
(node:18844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I also tried the new "vscode-serial-monitor.zip" you shared here:
https://github.com/microsoft/vscode-serial-monitor/issues/142#issuecomment-2049930857
with this version of the extension I can open the port, send and receive responses from the device successfully with all combinations of DTR/RTS.

**Comment by gcampbell-msft** [comment] 2024-04-15 16:00
@parmi93 Wow, thank you so much for your willingness to test and investigate so much. As far as I can tell, I think this confirms that the issue is strictly with the `.set` method. 

Could you confirm for me, what OS are you on? The thing I tried to add in this vsix: https://github.com/microsoft/vscode-serial-monitor/issues/159#issuecomment-2034645480 was simply checking which OS was being used. 

What value gets returned if you get the value of `process.platform` in a node program?

**Comment by parmi93** [comment] 2024-04-16 10:48
The value I get from `process.platform` is simply `linux`.

**Comment by gcampbell-msft** [comment] 2024-04-16 15:10
Hm, and to confirm, you said that this vsix (once changing the extension) only works for transmitting but not receiving? 
[vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/14998976/vscode-serial-monitor.zip)

**Comment by parmi93** [comment] 2024-04-16 15:33
https://github.com/microsoft/vscode-serial-monitor/issues/159#issuecomment-2034645480 -> Only works for transmitting

https://github.com/microsoft/vscode-serial-monitor/issues/142#issuecomment-2049930857 -> Works for transmitting and receiving

https://github.com/microsoft/vscode-serial-monitor/issues/159#issuecomment-2059329785 -> Works for transmitting and receiving

**Comment by gcampbell-msft** [comment] 2024-04-16 19:30
@parmi93 Okay if the most recent vsix works, I will try to get that in PR and merge that and have it in the pre-release in the coming days. Thanks!

**Comment by gcampbell-msft** [comment] 2024-04-16 20:48
@parmi93 If all goes well, this should be in pre-release tomorrow 👍

**Closed** 2024-06-20 19:57 UTC
Labels: bug, duplicate, fixed-pending-release
