### ISSUE TITLE
hex view: some data are not correctly displayed

### ISSUE THREAD

**Issue by axel-lebourhis** [microsoft/vscode-serial-monitor#139] opened 2023-10-10 11:50 UTC
Type: Bug Report

**Describe the bug**
- OS and Version: 
Remote SSH: 20.04.1 Ubuntu 
Local: Windows 10 Enterprise 19045
- VS Code Version: 1.83.0
- Serial Monitor Extension Version: Pre-release 0.10.231005001

I was looking for this hex display on the receive panel, glad to see it's supported in the pre-release version.
I gave it a try, and I noticed some data are not always correctly displayed.
In my case, I'm supposed to receive 00 80 FF 00 00
but the panel displays 00 FFFD FFFD 00 00
Looks line a sign or cast issue, not sure why the data is displayed on 2 bytes instead of 1.

**Comment by gcampbell-msft** [comment] 2023-11-17 17:06
@axel-lebourhis To help us be able to investigate this, reproduce it, and then hopefully diagnose the issue, is there any way that you can provide a project repro so that we can reproduce this erroneous output?

**Comment by embed-shaun** [comment] 2023-12-22 12:19
Hi @gcampbell-msft,

While I am not the original reporter, I also observe this issue. I can't provide a project that would assist with repro but I can explain the setup where I observe it, which is fairly trivial to reproduce.

OS and Version:  Windows 10 Pro 19045
VS Code Version: 1.85.1
Serial Monitor Extension Version: v0.11.0

In my case, I have an embedded device that I am listening to over serial. It is configured with Baud Rate 115200, Data Bits 8, Stop Bits 1, Parity None. 

If I configure the embedded device to transmit 0xFE followed by 0xED while monitoring with VSCode Serial Monitor in Hex mode, I will see 'fffd fffd' displayed in the output. I do not need to open a particular workspace or configure anything specific other than the COM port. 

Hopefully this helps, let me know if I can provide more information.

**Comment by embed-shaun** [comment] 2023-12-22 12:22
I should have followed through on#134 I see you have mentioned it is fixed pending release there.
 
 Probably worth marking this closed.

**Comment by gcampbell-msft** [comment] 2024-01-03 17:40
@embed-shaun @axel-lebourhis I'm curious if a fix I'm testing works for you, could you manually install this vsix? You'll need to download the zip, modify the extension to .vsix, and then manually install in VS Code. Thanks!

[vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/13821863/vscode-serial-monitor.zip)

**Comment by FlyinPancake** [comment] 2024-01-04 00:53
> @embed-shaun @axel-lebourhis I'm curious if a fix I'm testing works for you, could you manually install this vsix? You'll need to download the zip, modify the extension to .vsix, and then manually install in VS Code. Thanks!
> 
> [vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/13821895/vscode-serial-monitor.zip)

This resolves the issue!

**Comment by embed-shaun** [comment] 2024-01-05 11:59
> @embed-shaun @axel-lebourhis I'm curious if a fix I'm testing works for you, could you manually install this vsix? You'll need to download the zip, modify the extension to .vsix, and then manually install in VS Code. Thanks!
> 
> [vscode-serial-monitor.zip](https://github.com/microsoft/vscode-serial-monitor/files/13821895/vscode-serial-monitor.zip)

Hi, yes this appears to fix it. Here is before: 

![image](https://github.com/microsoft/vscode-serial-monitor/assets/154601192/7ed38125-cceb-401d-a649-675c8d1d7669)

and then after: 

![image](https://github.com/microsoft/vscode-serial-monitor/assets/154601192/96299902-0c60-4b1b-9d0f-bd2cbaa6a200)

Thank you for resolving :)

**Comment by gcampbell-msft** [comment] 2024-01-05 14:08
@FlyinPancake @embed-shaun Great! I am currently working on merging those changes and a new pre-release version should be out in the coming days with those changes.

**Comment by axel-lebourhis** [comment] 2024-01-05 15:14
Hi @gcampbell-msft , sorry for my lack of follow up, glad to know you've been able to resolve it.
I will retest when the pre-release is out.

Thanks !

**Comment by scilifen** [comment] 2024-01-06 11:44
I have met the same problem when using the SerialMonitor extension.
Windows 10, VScode Insider, SerialMonitor 0.11.0
if the sent byte is less or equal to 127, seems it can display correct forms, when the data sent is bigger than 128 (like 0x80), it will cause the error of "fffd".
![屏幕截图 2024-01-06 194251](https://github.com/microsoft/vscode-serial-monitor/assets/60095757/d71de90f-703a-4b16-abdc-1f1c4aa694b9)

**Comment by Jinying-Tang** [comment] 2024-01-15 04:46
The data I received also shows an error FFFD.
![image](https://github.com/microsoft/vscode-serial-monitor/assets/131565469/3eebd341-643a-4154-a8b7-9ab4778cc36a)

**Comment by Isaacbg84** [comment] 2024-02-22 22:23
Hello,

Im having the same error. Im developing a modbus reader with ESP32 MCU and when they send the data it gives me fffd always i send any data above 127. If i send data below that number it shows ok but not above that. What could be causing the problem?

**Comment by gcampbell-msft** [comment] 2024-02-23 14:24
@Isaacbg84 What version of the extension are you using? This issue should be solved on the pre-release channel. Could you test that?

**Comment by Muxmaeuschenstill** [comment] 2024-02-27 15:29
> @Isaacbg84 What version of the extension are you using? This issue should be solved on the pre-release channel. Could you test that?

Good day to you,
i've tried out pre release version of 'serial monitor' with vscode and vscode insiders. Both doesn't display correctly. The thing is, when i copy out the text with mouse right click and 'copy' and past it into another editor, then i can see the correct text. So it seem to be an displaying issue.

---- Opened the serial port COM4 ----
CLOCK_STATUS_1: 120
CLOCK_STATUS_2: 21
Samp Freq = 48000 Hz (48.0000 KHz)
![errortext](https://github.com/microsoft/vscode-serial-monitor/assets/41264593/15fc454a-5ca2-4b95-92d8-d1412a748e67)

**Comment by gcampbell-msft** [comment] 2024-02-29 14:28
@Muxmaeuschenstill Could you point out to me what exactly looks incorrect in your screenshot?

**Comment by Muxmaeuschenstill** [comment] 2024-03-01 13:25
> @Muxmaeuschenstill Could you point out to me what exactly looks incorrect in your screenshot?

Yes of course, thank you. Please look at the difference between the correct text, which i copied out with a right mouse click and the screen shot of the 'serial monitor' output. I ithink there are dublicates at the end of each line, like in the first line, 't COM4 ----' and in the second line '  120'. Additionally, the duplicate characters are not placed on the same line (best seen at the end of the third line of  the screenshot “2:   212”, where the position of the characters seems not to be correct.

I use another serial extension that works fine. So i'am sure not to send something wrong over the serial bus.

**Comment by gcampbell-msft** [comment] 2024-03-01 13:43
@Muxmaeuschenstill Ah, thank you for the clarification! I wasn't fully understanding, as this seems to be an independent issue. 

Could you please create a new issue for this? It would be most helpful since it's a separate issue than the hex display content. Additionally, it would be best if you could create a minimal repro that I could then attempt to reproduce the problem with. I haven't been able to reproduce this locally, but any help from you could help us solve this. Thanks!

**Comment by EV3NE** [comment] 2024-03-02 09:05
I can confirm the issue of not correct displaying hex values from **0x80** up. Serial Monitor version 0.11.0.
Setup: Ubuntu + 2x CP210x UART Bridge  connected each to other Tx to Rx, registered in system as /dev/ttyUSB0 and /dev/ttyUSB1.
### Verification that communication works correctly:
1) Terminal1:`cat /dev/ttyUSB1 | hexdump -v -e '/1 "%02x\n"'` (keeps running and printing incoming data)
2) Terminal2:`echo $'\x80' > /dev/ttyUSB0`
3) Terminal prints correctly value **80**
### Serial Monitor test:
1) Setup Serial Monitor to 9600 8N1 HEX /dev/ttyUSB1 (the CP210x are by default configured to 9600 8N1, but it can be verified by `stty -F /dev/ttyUSB0`)
2) Terminal:`echo $'\x80' > /dev/ttyUSB0`
3) Serial monitor shows **fffd**. 
4) Terminal:`echo $'\x7f' > /dev/ttyUSB0`
5) Serial monitor shows correctly **7f**.

**Comment by gcampbell-msft** [comment] 2024-03-04 14:23
@EV3NE This issue _should_ be fixed in the pre-release version. Could you test whether it works in the pre-release version? If not, then I will investigate as soon as I can.

**Comment by EV3NE** [comment] 2024-03-05 06:57
@gcampbell-msft I tested the preview versions, here are the results:
**Windows**
    - v0.11.240217001 (pre-release)
    - generated values 00-ff, SM shows 00-7f, then starts again 00-7f - **NOT OK**

**Linux**
    - v0.11.240217001 (pre-release)
    - generated values 00-ff, SM shows 00-ff - **OK**

There is another strange behavior, I'm not sure if intended, both in Win and Lin versions - the hex sometimes prints multiple values in the line (the number of values is not constant) and then prints only one value per line. This is repeating without any obvious patter, and is always different event when stopping the monitoring and starting again. This is probably different issue then the above mentioned, but I'm not sure, I should open new issue on this, or it can be fixed in this one.
Here is an example:

00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0e 0f 10
11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 20 
21 
22 
23 
24 
25 
26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32 33 34 35 
36 
37 
38 
39 
3a 
3b 3c 3d 3e 3f 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 
4d 
4e 
4f 
50 
51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 60 61 62 63
64 
65 
66

**Comment by gcampbell-msft** [comment] 2024-03-05 14:06
@EV3NE What data are you sending in the repro for the weird multiple lines issue? I'm wondering if that will help me investigate in trying to find what is wrong for that one. Thanks.

**Comment by EV3NE** [comment] 2024-03-05 19:15
@gcampbell-msft What concerns the interval, the problem disappears (on both Win, Lin), when I add a delay at least 10ms between each byte. With that delay, the HEX prints nicely 16 bytes per row, one row after another without any exception. But the data rate is already slow, as it is 9600kbps so I don't think it should be at some speed limit edge and to need any delay between the bytes.
On linux I tried full speed (without any delay between bytes) just between two terminals (via the USB-UART modules) and there was no problem, all data were received correctly.

### Ommiting 0x0d
I realized, that there is one more issue. The Serial Monitor is not displaying **0d**. This is actually visible in the SM output above, where is **0d** missing in the data, which are generated with +1 for loop. But I tried to send it separatelly too.
Again, I tested it between two linux terminals and everything was transcieved correctly and displayed too:

1. Terminal1: `cat /dev/ttyUSB1 | hexdump -v -e '1/1 " %02x" "\n"'`
2. Terminal2: `echo -n $'\x0d' > /dev/ttyUSB0`

This issue has different behavior between OSes:

- Linux:
    - sending: **0d**; receiving: nothing
- Windows:
    - sending: **0d**; receiving: nothing
    - sending: **8d**; receiving: nothing - this is consequence of aforementioned issue, where on Win, the SM displays correctly only values **00 - 7f**, and for input **80** up, the SM displays values again from **00** up, and when it comes to displaying **0d** (input **8d**), it is again missing in the outputs, which tells me, the problem is somewhere at the end of the processing.

Except **0d**, all other hex values are displayed.

**Closed** 2024-06-20 19:57 UTC
Labels: bug, fixed-pending-release

**Comment by ThorSporring** [comment] 2024-10-23 15:03
@EV3NE 
Did you ever get this fixed? I'm experiencing exactly the same with 0x0D value not being displayed. I've verified with other serial monitors that the byte actually gets sent, so something is up with this.
