### ISSUE TITLE
The second and third serial port windows can only be opened under the terminal tab

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode-serial-monitor#147] opened 2023-11-07 03:58 UTC
The second and third serial port windows can only be opened under the terminal label, which is very inconvenient to use.
The first serial port
![image](https://github.com/microsoft/vscode-serial-monitor/assets/25566498/2672407b-cc2d-4dad-bb43-44cba8adfcc8)
The second serial port
![image](https://github.com/microsoft/vscode-serial-monitor/assets/25566498/80f76ede-a6ca-4319-876b-14c3c98a8a56)
In previously released versions, both serial ports could be displayed simultaneously under the same serial port label.

**Comment by gcampbell-msft** [comment] 2023-11-07 11:21
@hongshui3000 You can drag and drop the Serial Monitor windows to be under the same view. You can drag the Serial Monitor (2) to the original Serial Monitor window (or vice versa). 

I'll close this issue for now since the issue is resolved, but please let me know if it still isn't working, and I can re-open the issue.

**Closed by gcampbell-msft** 2023-11-07 11:21 UTC
Labels: triage
