### ISSUE TITLE
Editable dropdown value for custom port & baudrate

### ISSUE THREAD

**Issue by adamalfath** [microsoft/vscode-serial-monitor#123] opened 2023-08-10 10:23 UTC
Type: Feature Request

Currently, the serial monitor only shows COM port from a physical device. Ports created virtually (like com0com, or similar program) don't appear. It would be great if it can accessing that.

Thanks.

**Comment by gcampbell-msft** [comment] 2023-08-10 13:18
@adamalfath Could you provide some context on the setup that you have that isn't appearing? I often do testing with com0com ports, thus, it should work with them. Maybe there is something more specific going on with your setup? 

Thanks!

**Comment by adamalfath** [comment] 2023-08-11 06:47
Ok I found new information to share.

So previously I use [com0com](https://com0com.sourceforge.net/) & [VSPE](https://eterlogic.com/) to create virtual port, and [YAT](https://sourceforge.net/projects/y-a-terminal/) as 2nd terminal reference. Here's what I do:

- Using com0com create port pair COM50-51
- Shown on device manager as expected (red box)
- Accessible via YAT, not shown on vscode-serial-monitor port dropdown selection
- Using VSPE create port pair COM100-101
- Not shown on device manager
- Accessible via YAT, not shown on vscode-serial-monitor port dropdown selection

Recently I try to use [VSPD](https://www.virtual-serial-port.org/vspd-post-download.html):

- Using VSPD create port pair COM10-11
- Shown on device manager (blue box)
- Accessible via YAT and vscode-serial-monitor

Also all the ports on the green box are listed on vscode-serial-monitor

![Screenshot_3](https://github.com/microsoft/vscode-serial-monitor/assets/19376004/d270a203-570a-41aa-9c47-51d5cf1b709c)

So my finding is that vscode-serial-monitor only listed ports that have **"Ports (COM & LPT)"** as their device type. It's okay I guess. It works as intended, it can open virtual ports. But in this mentioned case, vscode-serial-monitor become unusable since it won't let the user open the ports that are not listed on the dropdown selection.

I'll use VSPD for now. But it would be better if the program have more flexibility on how users can select the ports.

Thanks.

**Comment by adamalfath** [comment] 2023-08-11 07:04
It might be related to the UI interaction on #93 & #113.

I would suggest in addition to the option selectable via dropdown, the selection can also work like a textbox (or similar) where the user can input the custom value quickly without adding additional settings. It works for both port & baud rate input.

Reference from YAT:

![Screenshot_4](https://github.com/microsoft/vscode-serial-monitor/assets/19376004/dedea268-e009-40b4-b805-7c44552d93a1)
![Screenshot_5](https://github.com/microsoft/vscode-serial-monitor/assets/19376004/b0255eea-fc74-44a6-81b6-3579bfb85b03)

**Comment by gcampbell-msft** [comment] 2023-08-16 16:08
Ah, I found the issue that is a duplicate of this. Re-closing in favor of #113

**Closed by gcampbell-msft** 2023-08-16 16:08 UTC
Labels: enhancement
