### ISSUE TITLE
Not loading in Snapdragon/ARM PC

### ISSUE THREAD

**Issue by bjornh2** [microsoft/vscode-serial-monitor#214] opened 2024-12-14 10:31 UTC
When selecting the "Serial Monitor" tab in VS Code, there are only a blank area and a progress bar running on the top of the window. I have tried version 0.13.1 both in release and pre-release version with same problem, not loading.
I have unistalled the plugin and restated VS Code and rebooted the PC with no change.
I have a Lenovo Ideapad 5x 2-in-1 with Snapdragon(R) X Plus - X1P42100 - Qualcomm(R) Oryon(TM) CPU

**Comment by gcampbell-msft** [comment] 2024-12-16 14:02
@bjornh2 Are there any past versions of the extension that do work?

If not, this is likely a platform issue and we would need to investigate what about the ARM PC is breaking this. Also, have you noticed this on any other extensions?

**Comment by bjornh2** [comment] 2024-12-16 18:51
@gcampbell-msft
I think it's similar to a previous issue https://github.com/microsoft/vscode-serial-monitor/issues/148 
It might be the node-serialport issue https://github.com/serialport/node-serialport/issues/2570
I have tried version 0.10, 0.11, 0.12 and 0.13 but none works on my Snapdragon but it running om my Intel PC :)
The serial monitor in platformIO works on Snapdragon/ARM https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html
platformio.exe device monitor --environment esp32-s3-devkitm-1 --port COM4

**Comment by bjornh2** [comment] 2024-12-16 18:58
I have also installed some serial terminal apps and all works on my Snapdragon/ARM, for example thesis
https://apps.microsoft.com/detail/9NBLGGH43HDM?hl=neutral&gl=SE&ocid=pdpshare
https://apps.microsoft.com/detail/9P6M6GJSF3HN?hl=neutral&gl=SE&ocid=pdpshare

**Comment by bjornh2** [comment] 2024-12-16 19:30
No, I have not noticed this on any other extensions.
I'm working as software developer, so if I can be to any help just tell me :)

**Comment by bjornh2** [comment] 2024-12-16 19:45
I found this in the log (Show Logs -> Extension Host):
2024-12-16 20:38:39.627 [info] ExtensionService#_doActivateExtension ms-vscode.vscode-serial-monitor, startup: false, activationEvent: 'onView:vscode-serial-monitor.monitor0'
2024-12-16 20:38:39.678 [error] Activating extension ms-vscode.vscode-serial-monitor failed due to an error:
2024-12-16 20:38:39.678 [error] Error: No native build was found for platform=win32 arch=arm64 runtime=electron abi=128 uv=1 armv=8 libc=glibc node=20.18.1 electron=32.2.6
    loaded from: c:\Users\bjorn\.vscode\extensions\ms-vscode.vscode-serial-monitor-0.13.1\dist\node_modules\@serialport\bindings-cpp

**Comment by gcampbell-msft** [comment] 2024-12-17 20:26
@bjornh2 Thanks for the investigation. Unfortunately, you are correct and this is a duplicate of #148 and is due to the fact that our dependency on `node-serialport` which is the library we need to use. 

I will close this as a duplicate of #148 and please follow up with any thoughts, requests, on #148. Also, please upvote #148 as upvotes are commonly used to assess how many people are hitting the same issue.

**Closed by gcampbell-msft** 2024-12-17 20:26 UTC
Labels: triage
