### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by huahua0525** [microsoft/vscode-serial-monitor#48] opened 2022-10-13 07:49 UTC
Hopes to add the functions of sending and receiving hexadecimal data.

**Comment by hongshui3000** [comment] 2022-10-14 02:46
https://github.com/microsoft/vscode-serial-monitor/issues/5

**Comment by gcampbell-msft** [comment] 2022-10-20 12:41
Closing this as a duplicate of #5. Thanks @huahua0525 and @hongshui3000 !

**Closed by gcampbell-msft** 2022-10-20 12:41 UTC
Labels: triage

**Comment by gcampbell-msft** [comment] 2022-10-20 12:42
Also, I'd like to add that we do have this work item in our backlog. We don't currently have an ETA, but we are currently working to understand where it fits with our other feature requests. Thanks!
