### ISSUE TITLE
[Bug] Failed to open serial port on `/dev/ttyUSB0`

### ISSUE THREAD

**Issue by Scrappers-glitch** [microsoft/vscode-serial-monitor#32] opened 2022-07-28 14:20 UTC
Hello,

I am getting `**** Failed to open the serial port &#x2F;dev&#x2F;ttyUSB0. ****` when trying to open the serial port on `/dev/ttyUSB0` (which is the same port i am using for uploading and UART on my atmega328p and atmega32A).

I double checked the port if it was busy, but it is not in use while trying to open it via the plugin, i am using `vs code plugin v0.1.0`.

Thank you.

**Comment by gcampbell-msft** [comment] 2022-07-28 16:36
@Scrappers-glitch Feel free to try out the new release that was just released and let me know if that fixes your issues! If not, please let us know and we will look farther into it. Thanks for the feedback!

**Comment by gcampbell-msft** [comment] 2022-07-29 11:13
Closing as resolved, however, please re-open if the issue is persisting.

**Closed by gcampbell-msft** 2022-07-29 11:13 UTC
