### ISSUE TITLE
Clutter by tty's

### ISSUE THREAD

**Issue by catalinbalteanu** [microsoft/vscode-serial-monitor#158] opened 2024-01-07 18:34 UTC
On Linux the port drop-down gets filled with /dev/tty. Is there a setting to exlude those devices ?

![image](https://github.com/microsoft/vscode-serial-monitor/assets/6420199/5cf48884-a547-46a4-b201-e4022503519b)

**Comment by gcampbell-msft** [comment] 2024-01-08 13:38
To make sure I understand, this issue isn't saying that there is a bug where the ports you're interested aren't showing due to how many ports are populating, right? You're simply asking if you can filter them (feature request), so that it's not so cluttered? 

If so, I'll mark this as a feature request, and whether we implement it will be based on our backlog and likely on how much support it gets from the community. If you'd like for this issue to get highest priority, please *thumbs-up* react on the initial comment. 

Thanks!

**Comment by gcampbell-msft** [comment] 2024-01-08 14:39
I just noticed this is a duplicate of #133. Closing in favor of tracking there.

**Closed by gcampbell-msft** 2024-01-08 14:39 UTC
Labels: enhancement, needs-more-upvotes
