### ISSUE TITLE
not able to use extension with WSL2

### ISSUE THREAD

**Issue by tamba91** [microsoft/vscode-serial-monitor#111] opened 2023-06-07 12:52 UTC
Hi, the extension is not working within WSL2. If i try to open a serial monitor i get this message:
Error opening serial port: Error: Broken pipe, cannot set
 I can  perfectly flash the boards (Arduino Uno and esp8266) with VS Code extension and the arduino-cli installed in WSL2,  (using a custom version of arduino-cli installed in WSL2, not using bundled version of Arduino CLI).
The arduino-cli monitor works perfectly within the WSL2 terminal,
e.g. 

arduino-cli monitor -p /dev/ttyACM0

shows the output from the board

Of course if i try to open the serial monitor extension while the serial port is kept busy by arduino-cli monitor running in terminal i get this message:

Error opening serial port: Error: Device or resource busy, cannot open /dev/ttyACM0

if i type: 

fuser -k /dev/ttyACM0

and then try again to use the serial monitor extension i get again this message:

Error opening serial port: Error: Broken pipe, cannot set

I tried to paste this snippet in settings.json:

"remote.extensionKind": {
        "ms-vscode.vscode-serial-monitor": [
          "workspace"
        ]
}

but it does not work.
Thanks

**Comment by gcampbell-msft** [comment] 2023-07-20 14:14
@tamba91 Thanks for your feedback! Is there any way you could provide repro steps that would help me to reproduce and investigate this issue? 

Additionally, screenshots of your scenario may help me investigate. Thanks!

**Comment by tamba91** [comment] 2023-07-20 19:56
I’m not able to reproduce this issue again too. I tried many times but always failed. I suppose that there was a conflict between the arduino-cli serial monitor and the extension serial monitor, with the arduino-cli serial monitor not releasing the port properly, but i cannot be sure.
Thanks!

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: Garrett ***@***.***>
Inviato: giovedì 20 luglio 2023 16:14
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [microsoft/vscode-serial-monitor] not able to use extension with WSL2 (Issue #111)


@tamba91<https://github.com/tamba91> Thanks for your feedback! Is there any way you could provide repro steps that would help me to reproduce and investigate this issue?

Additionally, screenshots of your scenario may help me investigate. Thanks!

**Comment by gcampbell-msft** [comment] 2023-07-20 20:15
Thanks for the update! Since there currently isn't a repro, I'm closing the issue. Feel free to open another issue if you hit this problem again!

**Closed by gcampbell-msft** 2023-07-20 20:15 UTC
Labels: bug, needs-more-info
