### ISSUE TITLE
Decoding problem 

### ISSUE THREAD

**Issue by mohanex** [microsoft/vscode-serial-monitor#117] opened 2023-07-06 13:34 UTC
Hello,

I started using Serial monitor a few months ago and While using it for a RS232 com the received characters are not decoded.
See this [image](https://imgur.com/gallery/kQI4PDR)

**Comment by gcampbell-msft** [comment] 2023-07-06 13:38
What characters are you attempting to send? I also am curious if the issue is with your settings for stop bits and parity? My default is typically that most boards need 1 stop bit and  None for Parity. 

Looking forward to helping you, thanks!

**Comment by mohanex** [comment] 2023-07-06 14:22
I have this definition for my Transmission:
A single byte UART transmission is composed of 12 bits:
• 1 Start bit
• 8 Data bits
• 1 Parity bit (odd parity)
• 2 Stop bit.

**Comment by gcampbell-msft** [comment] 2023-07-06 14:34
@mohanex Got it, thanks for that clarification. 

In that case, my other thoughts are the following:
1) What data are you expecting to get back? What are you expecting it to look like? 
2) What baud rate is expected? I have confidence that you are using the correct baud rate, I only ask because occasionally, when the wrong baud rate is used, any data coming back will not look correct. 

Looking forward to getting this info.

**Comment by mohanex** [comment] 2023-07-06 15:10
@gcampbell-msft Thanks for your fast answers.
So I'm expecting to get back the same data I send, I interconnected the Rx and Tx of the "click MCP2542" (The card I'm using to convert UART to CAN, Not really important information).
For the baudrate; documenation mentions this :

**The baud rate is automatically detected.
The recommended baud rates are : 2M, 921.6k, 460.8k, 230.4k, 115.2k, 57.6k, 38.4k bit/s**

And i'm set to do 115.2k, thus I think I'm good.

**Comment by gcampbell-msft** [comment] 2023-07-07 20:56
@mohanex Out of curiosity, what happens if you simply send text over? Instead of sending a binary encoded string, use "Send as Text" and try sending something like "test". 

I'm trying to brainstorm what the issue might be and doing various tests like this might help me investigate.

**Comment by mohanex** [comment] 2023-07-10 08:43
When I send over some text I do not get anything back.

---- Sent utf8 encoded message: "test" ----
test

**Comment by gcampbell-msft** [comment] 2023-07-10 13:12
@mohanex Based on your output in both sending binary data and text data, I believe I know the answer. Currently, we encode the data that is sent to the device based on users settings in the UI. This is the `Send as ___` setting. However, we only currently support displaying in utf-8 ("regular text"), so therefore, when you simply return back binary data that you sent, we attempt to convert the buffer using a utf-8 encoding. 

This could be fixed by another request we have for the Serial Monitor, which is a hex view mode (could possibly be coupled with a "binary view"). With that in mind, I'm going to close this issue and point this to that feature request. "Hex view" is in our roadmap for being supported in our next release. 

Thank you!

**Comment by gcampbell-msft** [comment] 2023-07-10 13:12
This issue will be tracked by this feature request #5

**Closed by gcampbell-msft** 2023-07-10 13:12 UTC
Labels: investigating
