### ISSUE TITLE
Extention doesn't work in a VS code devcontainer

### ISSUE THREAD

**Issue by ToonVanEyck** [microsoft/vscode-serial-monitor#137] opened 2023-10-04 18:55 UTC
- OS and Version: 
    Windows 11
- VS Code Version: 
    Version: 1.82.3 (user setup)
    Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
    Date: 2023-10-02T10:51:22.294Z
    Electron: 25.8.1
    ElectronBuildId: 24153832
    Chromium: 114.0.5735.289
    Node.js: 18.15.0
    V8: 11.4.183.29-electron.0
    OS: Windows_NT x64 10.0.22621
- Serial Monitor Extension Version:
    v0.10.0

I am able to use the serial monitor under WSL2 but not in a vscode devcontainer. I first mentioned this issue in #77 .

The ports are available both in the devcontainer (left) and in wsl (right)
![image](https://github.com/microsoft/vscode-serial-monitor/assets/24410099/0ad9858f-9d10-44da-8df4-710030fd0363)
But the extension doesn't work in the devcontainer (left)
![image](https://github.com/microsoft/vscode-serial-monitor/assets/24410099/0799c065-eb08-48d5-98e1-13bd69ea7288)

**Comment by Helfezer** [comment] 2023-10-07 14:05
Hello, I have the same issue.
I work using Remote ssh from a windows10 computer to a ubuntu server.
There I'm able to use the extension but when I switch to my devcontainer I have the exact same screen.

- VS code version:
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
- Serial Monitor Extension Version:
v0.10.0

**Comment by biosbob** [comment] 2023-10-08 01:42
same issue for me, though my configuration is slightly different....  in my case, i'm actually running the vscode app **inside** a docker container....  the container already has access to a host serial port, as i verified using `picocom` from inside the terminal window within vscode....

though i have the extension installed in the vscode inside the container, i don't even see the Serial Monitor panel....

**Comment by jnz86** [comment] 2023-11-09 21:27
Same issue, but I'm using Linux-actual (Mint 21.2). 

Log from the extension:

```
2023-11-09T21:17:53.878Z [info] [vscode-serial-monitor] Activating extension
2023-11-09T21:17:54.033Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview -> host]: {"service":"monitorHost","type":"initialize","kind":"request","messageId":0}
2023-11-09T21:17:54.084Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview <- host]: {"service":"monitorHost","type":"initialize","kind":"exception","messageId":0,"payload":{"message":"spawn udevadm ENOENT","stack":"Error: spawn udevadm ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:283:19)\n\tat onErrorNT (node:internal/child_process:476:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","errno":-2,"code":"ENOENT","syscall":"spawn udevadm","path":"udevadm","spawnargs":["info","-e"]}}
2023-11-09T21:17:54.084Z [error] [vscode-serial-monitor.monitor] Failed to initialize serial monitor view {"message":"spawn udevadm ENOENT","stack":"Error: spawn udevadm ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:283:19)\n\tat onErrorNT (node:internal/child_process:476:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","errno":-2,"code":"ENOENT","syscall":"spawn udevadm","path":"udevadm","spawnargs":["info","-e"]}
```

I had a different `udevadm` error with Segger JLink install. I already knew udev was not installed.

Tried it with `apt install udev`

And... 

![image](https://github.com/microsoft/vscode-serial-monitor/assets/26825637/8cff4565-55b7-4957-8e8a-6752e8eca479)

I haven't confirmed function yet but it seems like it's going to work.

**Comment by handleandwheel** [comment] 2023-12-13 06:52
> Same issue, but I'm using Linux-actual (Mint 21.2).
> 
> Log from the extension:
> 
> ```
> 2023-11-09T21:17:53.878Z [info] [vscode-serial-monitor] Activating extension
> 2023-11-09T21:17:54.033Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview -> host]: {"service":"monitorHost","type":"initialize","kind":"request","messageId":0}
> 2023-11-09T21:17:54.084Z [debug] [vscode-serial-monitor.monitor] VsCodeHostAdapter [webview <- host]: {"service":"monitorHost","type":"initialize","kind":"exception","messageId":0,"payload":{"message":"spawn udevadm ENOENT","stack":"Error: spawn udevadm ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:283:19)\n\tat onErrorNT (node:internal/child_process:476:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","errno":-2,"code":"ENOENT","syscall":"spawn udevadm","path":"udevadm","spawnargs":["info","-e"]}}
> 2023-11-09T21:17:54.084Z [error] [vscode-serial-monitor.monitor] Failed to initialize serial monitor view {"message":"spawn udevadm ENOENT","stack":"Error: spawn udevadm ENOENT\n\tat ChildProcess._handle.onexit (node:internal/child_process:283:19)\n\tat onErrorNT (node:internal/child_process:476:16)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:82:21)","errno":-2,"code":"ENOENT","syscall":"spawn udevadm","path":"udevadm","spawnargs":["info","-e"]}
> ```
> 
> I had a different `udevadm` error with Segger JLink install. I already knew udev was not installed in the container.
> 
> Tried it with `apt install udev`
> 
> And...
> 
> ![image](https://private-user-images.githubusercontent.com/26825637/281874623-8cff4565-55b7-4957-8e8a-6752e8eca479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTA2MDEsIm5iZiI6MTcwMjQ1MDMwMSwicGF0aCI6Ii8yNjgyNTYzNy8yODE4NzQ2MjMtOGNmZjQ1NjUtNTViNy00OTU3LThlOGEtNjc1MmU4ZWNhNDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA2NTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NzFkMjY2MmI4MTlmYjEyYTk2NTYyMjE2MmE0MTZlZWZjOGI4MDk2YjcwNmEzOWNjZDczYTk5N2UzZmFlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tH0Br9NrVgv4RnFZhDCx1Zo0Kz3iBMYaA18i_9t5XXs)
> 
> I haven't confirmed function yet but it seems like it's going to work.

It works! Thanks!

**Comment by gcampbell-msft** [comment] 2024-01-08 14:32
It seems like this is fixed. The issue is that there is a dependency that must be installed by the user when attempting to use a dev container, `udev`. Please follow the steps listed by this comment: https://github.com/microsoft/vscode-serial-monitor/issues/137#issuecomment-1804710798. 

Closing this issue. I should note, we are still tracking an improvement request for this type of situation where the installation of the extension fails due to a dependency missing. #150

**Closed by gcampbell-msft** 2024-01-08 14:32 UTC
Labels: bug
