### ISSUE TITLE
how to send message periodily ?

### ISSUE THREAD

**Issue by wenyunhao** [microsoft/vscode-serial-monitor#178] opened 2024-05-08 02:31 UTC
as the title

**Comment by gcampbell-msft** [comment] 2024-05-21 14:38
We do not currently support this feature. I'm going to mark this as a duplicate of #92. However, if you feel this doesn't correctly encapsulate your request, please make another issue specifically requesting the feature. Thanks!

**Closed by gcampbell-msft** 2024-05-21 14:38 UTC
Labels: triage
