### ISSUE TITLE
Add font setting

### ISSUE THREAD

**Issue by rodrigofragadf** [microsoft/vscode-serial-monitor#161] opened 2024-01-20 20:12 UTC
I would like to be able to change the font setting in the terminal. I saw in another topic that the extension uses the `editor.fontFamily` setting but we often want to use a larger font for the text editor and a smaller one in the terminal to display more information. Adding this option would be greatly appreciated. Thank you for your attention.

**Comment by gcampbell-msft** [comment] 2024-01-22 14:02
@rodrigofragadf Does the current setting `vscode-serial-monitor.outputFontSize` not work for you? This should allow you to modify the output size of the serial monitor. 

Please let me know! Thanks!

**Comment by mrx23dot** [comment] 2024-01-29 11:45
For me it marks it as unknown
![image](https://github.com/microsoft/vscode-serial-monitor/assets/4163396/139fa8c9-7a96-4c4e-8725-3ea88ef6aa68)

I want to reduce font size so more can fit,
font size is bigger than one in terminal/problems tab 

Also documentation link seems unrealated/incomplete
https://learn.microsoft.com/en-us/cpp/embedded/?view=msvc-170

usually addon readme contains all setable options.

**Comment by gcampbell-msft** [comment] 2024-01-29 14:23
@mrx23dot Thanks for the note on the documentation, we'll work to get that updated. 

As for the setting, you should be able to view the setting in the project settings UI 
![image](https://github.com/microsoft/vscode-serial-monitor/assets/86264750/e015e534-7b84-4e14-8ec4-8eb3c155b6e7)

I've tested this setting and confirmed that it works, could you try modifying it this way?

**Comment by mrx23dot** [comment] 2024-01-29 14:26
I don't see settings like that 

![image](https://github.com/microsoft/vscode-serial-monitor/assets/4163396/e897142d-7da0-44dc-938a-f8f5c364b179)

in v0.7.0

**Comment by mrx23dot** [comment] 2024-01-29 15:06
Oh okay, looks like that's the last version for Vscode 1.70.x, any reason compatibility was dropped for the old VScode?

**Comment by rodrigofragadf** [comment] 2024-01-29 15:21
> @mrx23dot Thanks for the note on the documentation, we'll work to get that updated.
> 
> As for the setting, you should be able to view the setting in the project settings UI ![image](https://private-user-images.githubusercontent.com/86264750/300492702-e015e534-7b84-4e14-8ec4-8eb3c155b6e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDE4OTIsIm5iZiI6MTcwNjU0MTU5MiwicGF0aCI6Ii84NjI2NDc1MC8zMDA0OTI3MDItZTAxNWU1MzQtN2I4NC00ZTE0LThlYzQtOGViM2MxNTViNmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE1MTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZjhlYmNjOGVjYjJiNjg3NWEyYTkyMjE5N2E5YjJkN2E3ZWU0NjIzZDY4MTkzMWQxNTg5ZjAwOGRmOWY0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.urg1D_IOZ0v_0mkAvDidG5BboRtxtveQLTekWD29cgE)
> 
> I've tested this setting and confirmed that it works, could you try modifying it this way?

This worked for me, thanks!

**Comment by gcampbell-msft** [comment] 2024-01-29 15:47
> Oh okay, looks like that's the last version for Vscode 1.70.x, any reason compatibility was dropped for the old VScode?

Interesting, it should be still compatiable with those versions of VS Code, are you not able to update to 0.8.0 or higher?

**Comment by gcampbell-msft** [comment] 2024-01-29 15:51
No, you can't. As far as I know, there shouldn't be any reason why it's not compatible, I'll investigate and hopefully get a fix out for that in the pre-release channel soon.

**Comment by gcampbell-msft** [comment] 2024-01-29 18:19
@mrx23dot We indeed need to have 1.74 or higher. We only continually guarantee support for the latest version of VS Code. If you could please update so that you can get the font setting, that would be great!

Since we've gotten confirmation from @rodrigofragadf that the setting works, I'm going to close this issue as resolved.

**Closed by gcampbell-msft** 2024-01-29 18:19 UTC
Labels: needs-more-info

**Comment by mrx23dot** [comment] 2024-01-29 21:27
Unfortunately, last version that runs on Windows 7 is vscode 1.70.
But if we can't go lower then I have to live with it.
