### ISSUE TITLE
add setting to make terminal mode  by default

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-serial-monitor#132] opened 2023-09-19 01:36 UTC
Type: Feature Request

make this checked by default
![image](https://github.com/microsoft/vscode-serial-monitor/assets/1876302/2026a7d1-1651-4308-bbe7-7ee9d17e926a)

**Comment by gcampbell-msft** [comment] 2023-09-19 11:09
Marking this as a duplicate of #119. Thanks!

**Closed by gcampbell-msft** 2023-09-19 11:09 UTC
Labels: triage
